# Generated by Django 6.0 on 2025-12-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(verbose_name='Описание сайта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Названия сайта'),
        ),
    ]
