# Generated by Django 6.0 on 2025-12-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Данный', 'verbose_name_plural': 'Данные сайта'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Логотип'),
        ),
    ]
