# Generated by Django 6.0 on 2025-12-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_alter_settings_options_alter_settings_icon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='contact',
        ),
    ]
